import configs.pixel_means as pixel_means
data_path = 'data/'
# data_path = '/local_storage/users/sbroome/painface-recognition/'

config_dict = {
    # Program components
    'get_raw_sequence_data': True,
    'inference_only': False,
    'fine_tune': False,
    'save_features': False,
    'save_features_per_video': False,
    'video_level_mode': False,
    'train_video_level_features': False,
    'do_evaluate': True,
    'val_mode': 'subject',  # subject | fraction | no_val
    'train_mode': 'low_level',
    # Data
    'clip_list_pf': 'metadata/videos_overview_missingremoved.csv',
    'clip_list_lps': 'metadata/lps_videos_overview.csv',
    'pf_rgb_path': data_path + 'pf/jpg_224_224_25fps/',
    'lps_rgb_path': data_path + 'lps/jpg_224_224_25fps/',
    'pf_of_path': data_path + 'pf/jpg_224_224_25fps_OF_magnitude_cv2_2fpsrate/',
    'lps_of_path': data_path + 'lps/jpg_128_128_16fps_OF_magnitude_cv2_2fpsrate/',
    'pixel_mean': pixel_means.pf_rgb['mean'],
    'pixel_std': pixel_means.pf_rgb['std'],
    # 'model': '2stream_5d_add',
    'model': 'convolutional_LSTM',
    # 'model': 'clstm_functional',
    'fine_tune': False,
    'inference_only': True,
    # 'checkpoint': 'models/best_model_2stream_5d_add_122063.ckpt',
    'checkpoint': 'models/best_model_2stream_5d_add_testhejj.ckpt',
    'rgb_period': 1,  # Set to 10 if simonyan-like model
    'flow_period': 1,
    'input_width': 224,
    'input_height': 224,
    'color': True,
    'nb_labels': 2,
    'target_names': ['NO_PAIN', 'PAIN'],
    'nb_lstm_units': 2,
    'kernel_size': 3,
    'dropout_1': 0.7,
    'dropout_2': 0.7,
    'nb_epochs': 2,
    'early_stopping': 15,
    'optimizer': 'adadelta',
    'lr': 0.001,
    'round_to_batch': True,
    'seq_length': 10,
    'seq_stride': 10,
    'nb_workers': 1,
    'batch_size': 8,
    'nb_input_dims': 5,
    'val_mode': 'fraction',  # subject | fraction | no_val
    'val_fraction_value': 0.6,
    'monitor': 'val_binary_accuracy',
    'monitor_mode': 'max',
    'data_type': 'rgb',
    'nb_lstm_layers': 2,
    'aug_flip': 0,
    'aug_crop': 0,
    'aug_light': 0,
    'do_evaluate': True,
    'train_mode': 'low_level',  # keras | low_level
    'print_loss_every': 100,
    'resample_start_fraction_of_seq_length': 0.5,
    # Parameters for functional API C-LSTM
    'kernel_regularizer': None,
    'padding_clstm': 'valid',
    'strides_clstm': (1, 1),
    'dropout_clstm': 0.0,
    'pooling_method': 'max',
    'return_sequences': [True, False],
    'only_last_element_for_fc': 'no',
    'return_last_clstm': False,
    # Temporal mask things
    'normalization_mode': 'sequence',  # 'frame' | 'sequence'
    'temporal_mask_type': 'freeze',
    'nb_iterations_graddescent': 500,
    'focus_type': 'guessed',
    'lambda_1': 0.01,
    'lambda_2': 0.02,
    'tv_norm_p': 3,
    'tv_norm_q': 3,
    'verbose': True,
    'do_gradcam': True}
